parameters:
    timechimp.access_token: '%env(string:TIMECHIMP_ACCESS_TOKEN)%'

services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    ConnectHolland\TimechimpBundle\Api\Authentication\AccessTokenAuthentication:
        arguments:
            $apiKey: 'Bearer %timechimp.access_token%'

    ConnectHolland\TimechimpBundle\Api\Client:
        public: true
        lazy: true
        factory: [ConnectHolland\TimechimpBundle\Api\Client, create]
        arguments:
            $httpClient: ~
            $authentication: '@ConnectHolland\TimechimpBundle\Api\Authentication\AccessTokenAuthentication'
