parameters:

services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    timechimp.authentication_registry:
        class: 'Jane\OpenApiRuntime\Client\Plugin\AuthenticationRegistry'
        arguments:
            $authenticationPlugins:
                - '@ConnectHolland\TimechimpBundle\Api\Authentication\AccessTokenAuthentication'

    ConnectHolland\TimechimpBundle\Api\Authentication\AccessTokenAuthentication:
        arguments:
            - 'Bearer %timechimp.access_token%'

    ConnectHolland\TimechimpBundle\Api\Client:
        public: true
        lazy: true
        factory: [ConnectHolland\TimechimpBundle\Api\Client, create]
        arguments:
            $httpClient: ~
            $additionalPlugins: ['@timechimp.authentication_registry']
