parameters:

services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    ConnectHolland\TimechimpBundle\Api\Authentication\AccessTokenAuthentication:
        arguments:
            - 'Bearer %timechimp.access_token%'

    ConnectHolland\TimechimpBundle\Api\Client:
        public: true
        lazy: true
        factory: [ConnectHolland\TimechimpBundle\Api\Client, create]
        arguments:
            $httpClient: ~
            $additionalPlugins: ['@ConnectHolland\TimechimpBundle\Api\Authentication\AccessTokenAuthentication']
